# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gmail.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.protobufs import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gmail.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgmail.proto\x1a\x0c\x63ommon.proto\"4\n\x10GmailAuthRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x02 \x01(\t2\xae\x01\n\x08GmailApi\x12*\n\x04\x61uth\x12\x11.GmailAuthRequest\x1a\r.AuthResponse\"\x00\x12 \n\x0bget_dialogs\x12\x05.User\x1a\x08.Dialogs\"\x00\x12+\n\x0cget_messages\x12\x0e.DialogRequest\x1a\t.Messages\"\x00\x12\'\n\x0csend_message\x12\x05.Send\x1a\x0e.StatusMessage\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_GMAILAUTHREQUEST = _descriptor.Descriptor(
  name='GmailAuthRequest',
  full_name='GmailAuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='GmailAuthRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='credentials', full_name='GmailAuthRequest.credentials', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['GmailAuthRequest'] = _GMAILAUTHREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GmailAuthRequest = _reflection.GeneratedProtocolMessageType('GmailAuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _GMAILAUTHREQUEST,
  '__module__' : 'gmail_pb2'
  # @@protoc_insertion_point(class_scope:GmailAuthRequest)
  })
_sym_db.RegisterMessage(GmailAuthRequest)



_GMAILAPI = _descriptor.ServiceDescriptor(
  name='GmailApi',
  full_name='GmailApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=84,
  serialized_end=258,
  methods=[
  _descriptor.MethodDescriptor(
    name='auth',
    full_name='GmailApi.auth',
    index=0,
    containing_service=None,
    input_type=_GMAILAUTHREQUEST,
    output_type=common__pb2._AUTHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_dialogs',
    full_name='GmailApi.get_dialogs',
    index=1,
    containing_service=None,
    input_type=common__pb2._USER,
    output_type=common__pb2._DIALOGS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_messages',
    full_name='GmailApi.get_messages',
    index=2,
    containing_service=None,
    input_type=common__pb2._DIALOGREQUEST,
    output_type=common__pb2._MESSAGES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_message',
    full_name='GmailApi.send_message',
    index=3,
    containing_service=None,
    input_type=common__pb2._SEND,
    output_type=common__pb2._STATUSMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GMAILAPI)

DESCRIPTOR.services_by_name['GmailApi'] = _GMAILAPI

# @@protoc_insertion_point(module_scope)
