# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.protobufs import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08tg.proto\x1a\x0c\x63ommon.proto\"L\n\rTgAuthRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x11\n\tcode_hash\x18\x04 \x01(\t2\xa3\x02\n\x05TgApi\x12\'\n\x04\x61uth\x12\x0e.TgAuthRequest\x1a\r.AuthResponse\"\x00\x12 \n\x0bget_dialogs\x12\x05.User\x1a\x08.Dialogs\"\x00\x12+\n\x0cget_messages\x12\x0e.DialogRequest\x1a\t.Messages\"\x00\x12\'\n\x0csend_message\x12\x05.Send\x1a\x0e.StatusMessage\"\x00\x12-\n\tmark_read\x12\x0e.DialogRequest\x1a\x0e.StatusMessage\"\x00\x12\x1e\n\ttest_file\x12\x05.Text\x1a\x06.Chunk\"\x00\x30\x01\x12*\n\x12get_id_by_username\x12\t.UserName\x1a\x07.UserId\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_TGAUTHREQUEST = _descriptor.Descriptor(
  name='TgAuthRequest',
  full_name='TgAuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='TgAuthRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone', full_name='TgAuthRequest.phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='TgAuthRequest.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code_hash', full_name='TgAuthRequest.code_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['TgAuthRequest'] = _TGAUTHREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TgAuthRequest = _reflection.GeneratedProtocolMessageType('TgAuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _TGAUTHREQUEST,
  '__module__' : 'tg_pb2'
  # @@protoc_insertion_point(class_scope:TgAuthRequest)
  })
_sym_db.RegisterMessage(TgAuthRequest)



_TGAPI = _descriptor.ServiceDescriptor(
  name='TgApi',
  full_name='TgApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=396,
  methods=[
  _descriptor.MethodDescriptor(
    name='auth',
    full_name='TgApi.auth',
    index=0,
    containing_service=None,
    input_type=_TGAUTHREQUEST,
    output_type=common__pb2._AUTHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_dialogs',
    full_name='TgApi.get_dialogs',
    index=1,
    containing_service=None,
    input_type=common__pb2._USER,
    output_type=common__pb2._DIALOGS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_messages',
    full_name='TgApi.get_messages',
    index=2,
    containing_service=None,
    input_type=common__pb2._DIALOGREQUEST,
    output_type=common__pb2._MESSAGES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_message',
    full_name='TgApi.send_message',
    index=3,
    containing_service=None,
    input_type=common__pb2._SEND,
    output_type=common__pb2._STATUSMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='mark_read',
    full_name='TgApi.mark_read',
    index=4,
    containing_service=None,
    input_type=common__pb2._DIALOGREQUEST,
    output_type=common__pb2._STATUSMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='test_file',
    full_name='TgApi.test_file',
    index=5,
    containing_service=None,
    input_type=common__pb2._TEXT,
    output_type=common__pb2._CHUNK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_id_by_username',
    full_name='TgApi.get_id_by_username',
    index=6,
    containing_service=None,
    input_type=common__pb2._USERNAME,
    output_type=common__pb2._USERID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TGAPI)

DESCRIPTOR.services_by_name['TgApi'] = _TGAPI

# @@protoc_insertion_point(module_scope)
